/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/recipe/edit/[id]`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/../components/home/quick-actions-modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/diary` | `/diary`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/health` | `/health`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/quick-actions-stub` | `/quick-actions-stub`; params?: Router.UnknownInputParams; } | { pathname: `/meal/ai-vision`; params?: Router.UnknownInputParams; } | { pathname: `/recipe/create`; params?: Router.UnknownInputParams; } | { pathname: `/ingredient/[name]`, params: Router.UnknownInputParams & { name: string | number; } } | { pathname: `/recipe/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/recipe/edit/[id]`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/home/quick-actions-modal`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/diary` | `/diary`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/health` | `/health`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/quick-actions-stub` | `/quick-actions-stub`; params?: Router.UnknownOutputParams; } | { pathname: `/meal/ai-vision`; params?: Router.UnknownOutputParams; } | { pathname: `/recipe/create`; params?: Router.UnknownOutputParams; } | { pathname: `/ingredient/[name]`, params: Router.UnknownOutputParams & { name: string; } } | { pathname: `/recipe/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/recipe/edit/[id]${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `/../components/home/quick-actions-modal${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/register${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/diary${`?${string}` | `#${string}` | ''}` | `/diary${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/health${`?${string}` | `#${string}` | ''}` | `/health${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/quick-actions-stub${`?${string}` | `#${string}` | ''}` | `/quick-actions-stub${`?${string}` | `#${string}` | ''}` | `/meal/ai-vision${`?${string}` | `#${string}` | ''}` | `/recipe/create${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/recipe/edit/[id]`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/../components/home/quick-actions-modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/diary` | `/diary`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/health` | `/health`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/quick-actions-stub` | `/quick-actions-stub`; params?: Router.UnknownInputParams; } | { pathname: `/meal/ai-vision`; params?: Router.UnknownInputParams; } | { pathname: `/recipe/create`; params?: Router.UnknownInputParams; } | `/ingredient/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/recipe/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/ingredient/[name]`, params: Router.UnknownInputParams & { name: string | number; } } | { pathname: `/recipe/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
